@startuml CL_ActivityModule
' requirement REQ-00024-1

!startsub ActivityModule

namespace render.activity {
  class isActivity <<function>> {
    + isActivity()
  }
  class activityToIr <<function>> {
    + activityToIr()
  }
  class actionText <<function>> {
    + actionText()
  }
  class paren <<function>> {
    + paren()
  }
}

!endsub

@enduml
