@startuml CL_EngineModule
' requirement REQ-00002-1
' requirement REQ-00006-1
' requirement REQ-00016-1

!startsub EngineModule

namespace render.engine {
  class renderSvg <<function>> {
    + renderSvg(input: unknown, opts: RenderOptions) : string
  }
}

!endsub

@enduml
