@startuml CL_FiltersModule
' requirement REQ-00005-1

!startsub FiltersModule

namespace render.filters {
  class stripSections <<function>> {
    + stripSections(ir: RenderIr) : RenderIr
  }
  class flattenContainers <<function>> {
    + flattenContainers(ir: RenderIr) : RenderIr
  }
  class hideNotes <<function>> {
    + hideNotes(ir: RenderIr) : RenderIr
  }
}

!endsub

@enduml
