@startuml CL_FrontendModule
' requirement REQ-00003-1
' requirement REQ-00007-1

' requirement REQ-00013-1
' requirement REQ-00023-1

!startsub FrontendModule

namespace render.frontend {
  class configureParser <<function>> {
    + configureParser()
  }
  class pumlToIr <<function>> {
    + pumlToIr()
  }
  class load <<function>> {
    + load()
  }
  class packagedAssets <<function>> {
    + packagedAssets()
  }
}

!endsub

@enduml
