@startuml CL_FrontendModule
' requirement REQ-00003-1
' requirement REQ-00007-1

' requirement REQ-00013-1

!startsub FrontendModule

namespace render.frontend {
  class configureParser <<function>> {
    + configureParser(next: ParserAssets) : void
  }
  class pumlToIr <<function>> {
    + pumlToIr(source: string) : Promise<RenderIr>
  }
}

!endsub

@enduml
