@startuml CL_LinksModule
' requirement REQ-00018-1

!startsub LinksModule

namespace render.links {
  class applyLinks <<function>> {
    + applyLinks()
  }
  class entryFor <<function>> {
    + entryFor()
  }
  class shortName <<function>> {
    + shortName()
  }
}

!endsub

@enduml
