@startuml CL_Render
' requirement REQ-00001-1
' requirement REQ-00002-1
' requirement REQ-00003-1
' requirement REQ-00004-1
' requirement REQ-00005-1
' requirement REQ-00006-1
' requirement REQ-00007-1
' requirement REQ-00008-1
' requirement REQ-00009-1
' requirement REQ-00010-1
' requirement REQ-00011-1
' requirement REQ-00017-1
' requirement REQ-00018-1

!startsub IrModule
!includesub ./CL_IrModule.puml!IrModule
!endsub

!startsub IrValidationError
!includesub ./CL_IrValidationError.puml!IrValidationError
!endsub

!startsub EngineModule
!includesub ./CL_EngineModule.puml!EngineModule
!endsub

!startsub SharedModule
!includesub ./CL_SharedModule.puml!SharedModule
!endsub

!startsub SequenceModule
!includesub ./CL_SequenceModule.puml!SequenceModule
!endsub

!startsub FiltersModule
!includesub ./CL_FiltersModule.puml!FiltersModule
!endsub

!startsub LinksModule
!includesub ./CL_LinksModule.puml!LinksModule
!endsub

!startsub FrontendModule
!includesub ./CL_FrontendModule.puml!FrontendModule
!endsub

!startsub ActivityModule
!includesub ./CL_ActivityModule.puml!ActivityModule
!endsub

!startsub ServeModule
!includesub ./CL_ServeModule.puml!ServeModule
!endsub

!startsub CliModule
!includesub ./CL_CliModule.puml!CliModule
!endsub

@enduml
