@startuml CL_SequenceModule
' requirement REQ-00009-1

' requirement REQ-00019-1

!startsub SequenceModule

namespace render.sequence {
  class renderSequenceSvg <<function>> {
    + renderSequenceSvg(ir: RenderIr) : string
  }
}

!endsub

@enduml
