@startuml CL_ServeModule
' requirement REQ-00011-1

!startsub ServeModule

namespace render.serve {
  class renderFile <<function>> {
    + renderFile(file: string, state: ViewState) : Promise<string>
  }
  class startServer <<function>> {
    + startServer(file: string, port: number) : Promise<Serving>
  }
}

!endsub

@enduml
