@startuml CL_SequenceModule
' requirement REQ-00009-1

!startsub SequenceModule

namespace render.sequence {
  class "<<module>>" as SequenceModule {
    + renderSequenceSvg(ir: RenderIr) : string
  }
  SequenceModule ..> render.ir.IrModule
  SequenceModule ..> render.shared.SharedModule
}

!endsub

@enduml
