@startuml CL_ServeModule
' requirement REQ-00011-1

!startsub ServeModule

namespace render.serve {
  class renderFile <<function>> {
    + renderFile()
  }
  class startServer <<function>> {
    + startServer()
  }
}

!endsub

@enduml
