@startuml CL_SharedModule
' requirement REQ-00002-1
' requirement REQ-00012-1
' requirement REQ-00015-1
' requirement REQ-00017-1

!startsub SharedModule

namespace render.shared {
  class esc <<function>> {
    + esc()
  }
  class idPrefix <<function>> {
    + idPrefix()
  }
  class memberMarkup <<function>> {
    + memberMarkup()
  }
  class refAttrs <<function>> {
    + refAttrs()
  }
  class linked <<function>> {
    + linked()
  }
  class tooltip <<function>> {
    + tooltip()
  }
  class svgRoot <<function>> {
    + svgRoot()
  }
  class noticeMarkup <<function>> {
    + noticeMarkup()
  }
  class splitParams <<function>> {
    + splitParams()
  }
}

!endsub

@enduml
